### ISSUE TITLE
[Proposal] Command line interface

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-renderer#25]

**Comment by Siemienik** [comment]
proposed usages:

```
# 1 two arguments
xlr template.xlsx '{"jsonData":true"}'

# 2. via pipe
cat vm.json | xlr template.xlsx

# 3. --json-inline to change order
xlr --json-inline '{"someData":true}' template.xlsx

# 4. proposal: supporting xml inline
xlr --xml-inline "<someData></someData>" template.xlsx

# 5. from json file
xlr --json vm.json template.xlsx

# 6. proposal: from xml file
xlr --xml-file vm.xml template.xlsx
```

## todo in this issue:

* [ ] 1. two arguments
* [ ] 2. via pipe

## leftovers: (ordered by priority:

* [ ] 3. --json-inline to change order
* [ ] 5. from json file
* [ ] 4. proposal: supporting xml inline
* [ ] 6. proposal: from xml file
